welcome_message = "Enter 'start' to start the game!"
enter_name_message = 'Enter your Name!'
start_command_message = 'start'
help_command_message = 'help'
show_scores_command_message = 'show scores'
exit_command_message = 'exit'
game_over_message = 'Game Over!'
good_bye_message = 'Good bye!'
enter_attack_message = 'Enter your attack: Should be from 1 to 3'
enter_defense_message = 'Enter your defence: Should be from 1 to 3'
draw_message = "It's a draw!"
win_message = "You attacked successfully!"
defeat_message = "You missed!"
result_message = "Total scores: "
